### ISSUE TITLE
AuthenticationExtension.cs methods not called by SSRS

### ISSUE THREAD

**Issue by r-coursera1** [sonrai-LLC/ExtRSAuth#1]
Hey,
I'm not sure if this is the right place to ask but I wanted to get your experience.
I have forms authentication almost working. Pretty soon I want to try something similar to this repo (automatic login)
I just have 2 major concerns:-

1) Some of the interface methods never seem to get called by SSRS, not sure if you ran into this..

        public bool LogonUser(string userName, string password, string authority){}
        public bool IsValidPrincipalName(string principalName){}
        public string LocalizedName

     I put `NLog` logging in each of these methods but don't see anything.., howerver `NLog` works on `Login.aspx.cs`.
    

2) How would a user get Logged out ?
 I don't think we can add buttons to the MS SSRS portal, right ?

**Comment by cfitzg** [comment]
1). LogonUser() is not needed in the default implementation but you could certainly implement it if you wanted to.

IsValidPrincipalName and LocalizedName are also not required. The former is for AD lookups (ExtRSAuth has no dependency on AD), and I don't quite remember what LocalizedName was for in the MS Custom Security example which this is based upon. It doesn't make things any less or more secure though.

2). Like MS' Custom Security example, ExtRSAuth generates a cookie on client browser with a token/hash value. The cookie is called "sqlAuthCookie". This cookie is only valid for a relatively short period of time (30 minutes maybe? I'll check documentation and test in the next commit). You can clear cookies to force a logout. Otherwise the SSRS session associated with the sqlAuthCookie will expire after some time.

Thanks for bringing your concerns to my attention. I hope I have addressed at least some of your concerns. Let me know if any other concerns or need answers on any of the behavior.

**Comment by cfitzg** [comment]
Ok, I did some digging and the default session length for the sqlAuthCookie is 6 hours (or 360 minutes or 21,600 seconds).

The best way I've seen to implement Logout functionality for this sqlAuthCookie involved in SSRS Custom Security is this: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/5e33949d-7757-45d1-9c43-6dc3911c3ced/how-do-you-logout-of-report-manager?forum=sqlreportingservices

I don't have a need for logout with my usage of ExtRSAuth, but now that you brought this to my attention, I plan to implement the above Logout functionality as a callable function.

I hope that helps. Let me know if you have any other questions, else I'll mark this as resolved.

**Comment by cfitzg** [comment]
(the Logout functionality is basically just an automated way of clearing the connected client's sqlAuthCookie)

            HttpCookie sqlAuthCookie = new HttpCookie("sqlAuthCookie", "sqlAuthCookie");
            sqlAuthCookie.Expires = DateTime.Now.AddDays(-1); //makes cookie expired
            HttpContext.Current.Response.Cookies.Add(sqlAuthCookie); //overwrites existing sqlAuthCookie w/expired one
